# Generated by Django 5.0.3 on 2024-04-26 15:58

import Comptoire.models.models_Entite_marchandise
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etatoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatOperation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EtatsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatDisignation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonArtIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBonArtOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBonCMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneFactureAvoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneFactureProfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_art', models.IntegerField()),
                ('qte', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiseEtatSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatimprimable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PayementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayementEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayementSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('propreot', models.IntegerField()),
                ('editeur', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemiseSousTraitent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('etablissement', models.IntegerField()),
                ('montant', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeClient', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypePayement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePayement', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSS', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('credit_init', models.FloatField()),
                ('registre_commerce', models.CharField(max_length=50)),
                ('NIF', models.CharField(max_length=50)),
                ('NIS', models.CharField(max_length=50)),
                ('ART', models.CharField(max_length=50)),
                ('BP', models.CharField(max_length=50)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatsclient')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typeclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MvtStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('entree', models.BooleanField()),
                ('sortie', models.BooleanField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.etablissement')),
                ('id_Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.article')),
            ],
        ),
        migrations.CreateModel(
            name='S_famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
                ('id_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.famille')),
            ],
        ),
        migrations.CreateModel(
            name='S_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
                ('P_achat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('P_vente', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('P_min', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('barrcode', models.CharField(max_length=13, unique=True, validators=[Comptoire.models.models_Entite_marchandise.validate_barcode])),
                ('fournisseur_best', models.IntegerField()),
                ('id_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.article')),
                ('id_S_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.s_famille')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.etablissement')),
                ('id_Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.article')),
            ],
        ),
        migrations.CreateModel(
            name='SousTraitent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSS', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('credit_init', models.FloatField()),
                ('registre_commerce', models.CharField(max_length=50)),
                ('NIF', models.CharField(max_length=50)),
                ('NIS', models.CharField(max_length=50)),
                ('ART', models.CharField(max_length=50)),
                ('BP', models.CharField(max_length=50)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatsclient')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typeclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSS', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('credit_init', models.FloatField()),
                ('registre_commerce', models.CharField(max_length=50)),
                ('NIF', models.CharField(max_length=50)),
                ('NIS', models.CharField(max_length=50)),
                ('ART', models.CharField(max_length=50)),
                ('BP', models.CharField(max_length=50)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatsclient')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typeclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSS', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('credit_init', models.FloatField()),
                ('registre_commerce', models.CharField(max_length=50)),
                ('NIF', models.CharField(max_length=50)),
                ('NIS', models.CharField(max_length=50)),
                ('ART', models.CharField(max_length=50)),
                ('BP', models.CharField(max_length=50)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatsclient')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typeclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactureProfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactureAvoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonTranzition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonCMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonArtOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonArtIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('propretaire', models.IntegerField()),
                ('montant', models.FloatField()),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.etatoperations')),
                ('imprime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.liseetatsortie')),
                ('type_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comptoire.typepayement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
